# conda env create -f environment.yml
name: c3s-catalogs
channels:
  - conda-forge
dependencies:
  - pip
  - python=3
  - jupyterlab
  - pandas >=2
  - intake <2
  - dask
  - fsspec
  - requests
  - aiohttp
  - yaml
