# conda env create -f environment.yml
name: c3s-notebooks
channels:
  - conda-forge
dependencies:
  - pip
  - python=3
  - jupyterlab
  - pandas
  - intake
  - dask
  - fsspec
  - requests
  - aiohttp
  - yaml
